### ISSUE TITLE
Failing ThrowsOnIncorrectDataType test

### ISSUE THREAD

**Issue by andysturrock** [drewnoakes/msgpack-strict#6]
This is the expected exception message for when we are trying to read an int but actually it's a double on the wire:
`Assert.Equal("Unexpected type for \"score\". Expected int, got double.", ex.Message);`
Given all we get from `TryReadInt32` is true or false, did you have some plan for how to actually create this specific message?
How about adding a method to the custom deserialiser something like:
`bool TryReadNextType(out Type result)`

What do you think?

**Comment by drewnoakes** [comment]
`TryPeekFormat` was added in c0b987262e547666e87204643f20bed7aaad620f and used it to create a better exception message in 758d550de381fc76f20333fd5628758647d23744.
