### ISSUE TITLE
Were you thinking of writing a custom serialiser too?

### ISSUE THREAD

**Issue by andysturrock** [drewnoakes/msgpack-strict#7]
We have a custom packer, so were you thinking about a custom serialiser to drive it?  On my machine the performance figures seem to vary depending on how many times it has been run, but in general the safe packer (1700ms) outperforms the unsafe one (2000ms), which outperforms the cli one (2700ms).

I've written a very simple reflection based custom serialiser here: https://github.com/andysturrock/msgpack-strict/tree/reflective-serialiser
I might change it to emit based just for fun and to see how much quicker it is.

Is there anything that the msgpack-cli serialiser doesn't provide?  Were you thinking of contributing the whole strict deserialisation back to msgpack-cli?  I think that would be my preference.

**Comment by drewnoakes** [comment]
Custom serialiser was added in 8ef14b58f8b02872c1e046ab72c5f3356ff7afe3 and extended in subsequent commits. Again, this all happend while I was on the plane before I saw you'd also done some work on this.

Those performance stats are interesting. The unsafe version is fastest on my machine:

> thisBytePackTime=1309.2738, thisUnsafeTime=926.0927, thatPackTime=1123.4727

As for merging into MsgPack.Cli, I'm not sure how compatible this code is. The ideas are certainly portable. That's a very general lib, and this benefits from specifically targeting DTOs. I'd previously [suggested this kind of thing](https://github.com/msgpack/msgpack-cli/issues/135) on the project but nothing came back.

So currently this lib round-trips DTOs quite nicely. There will be some missing bits (like sending `DateTime` or complex struct types) but they shouldn't be too hard to address.

I haven't yet done any profiling/optimisation beyond the crude timings in `PackPerfFaceOff`.
